name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: '3.10'
          - os: ubuntu-24.04
            python-version: '3.12'
          - os: ubuntu-26.04
            python-version: '3.14'

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: PIP cache
      uses: actions/cache@v6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-python${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: UV cache
      uses: actions/cache@v6
      with:
        path: ~/.local/share/uv/cache
        key: ${{ runner.os }}-uv-python${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'requirements/uv-3.10.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-python${{ matrix.python-version }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions uv
    - name: Test with tox
      run: |
        tox
